### ISSUE TITLE
Loess model for chum in migration timing plot

### ISSUE THREAD

**Issue by sarah-friesen** [HakaiInstitute/jsp-time-series#12]
Why is a loess model used for cumulative catch of chum in the migration-timing-plot chunk of the Migrations_Observations_Report script and a logistic regression model used for all other species? I'm not sure how this might change inter-species comparability. If we can't use a logistic regression model for chum, would it make sense to switch to using a loess model for all species?

**Comment by Br-Johnson** [comment]
I used a LOESS model for chum in 2017 because the data did not fit the assumptions of a logistic model for chum in 2017. The reason for that is because we did not capture the tail end of the chum migration in 2017 because we ended sampling too soon. In fact the line produced in this plot that you are speaking about:

https://github.com/HakaiInstitute/jsp-time-series/blob/b4f46e4addbf718f828bb356c3980e727b171042/scripts/Migration_Observations_Report.Rmd#L403

None of the migration statistics rely on this model (loess or logistic)—they are mainly an aid to visualization. As you'll notice all the migration timing parameters are derived from medians and IQRs which make no assumptions of the underlying distribution in the data.
