### ISSUE TITLE
data_wrangle Sea Lice Data - check NAs

### ISSUE THREAD

**Issue by salmonsam** [HakaiInstitute/jsp-time-series#14]
The data may be fine, but there are a lot of NA's in the sea lice data, and quite a few drop_na() functions, so it would be good to go through and make sure that all the data is there that should be. For instance, in the 'motile_lice' file, it looks like fish were either lab-loused or field-loused, but not both. Julian thinks there may have been some overlap with fish that were field and lab loused in 2017, but none show up in the 'motile_lice' file. I've tried to troubleshoot this myself but I'm not familiar with the licing stuff at all, so might be better for Julian or Brett to review this.

**Comment by Br-Johnson** [comment]
The generation of the sea-lice time series is a bit of a challenge because the data are being combined from a number of disparate sources. It took me quite a bit of time, and a lot of not so intuitive coding to make sure the sealice data are complete. 

https://github.com/HakaiInstitute/jsp-time-series/blob/28013b6ff4119a3c30edacc5440f615a33b191f9/scripts/data_wrangle.Rmd#L140

When fish were field liced and lab loused, preference was given to data generated in the lab because we assume lab data to be slightly more reliable. 

I feel nervous for someone to go down this rabbit hole and I think there are higher priorities than addressing this currently.
